# Generated by Qodo Gen
from func import _write
import unittest

class Test_Write(unittest.TestCase):

    # Counts words correctly in a file without special characters
    def test_counts_words_correctly(self):
        with open('assets/original_file.txt', 'w') as f:
            f.write("This is a test file with words only")
        result = _write()
        self.assertEqual(result, 8)

    # Handles empty files without errors
    def test_handles_empty_file(self):
        with open('assets/original_file.txt', 'w') as f:
            f.write("")
        result = _write()
        self.assertEqual(result, 0)

    # Processes files with only special characters correctly
    def test_processes_special_characters_only(self):
        with open('assets/original_file.txt', 'w') as f:
            f.write("!@#$%^&*()_+,./<>?;:[]{}|1234567890")
        result = _write()
        self.assertEqual(result, 0)