# Generated by Qodo Gen
from func import function
import unittest

class TestFunction(unittest.TestCase):

    # Adds a line with '*' after all lines if there are lines without commas in 'assets/original_file.txt'
    def test_add_asterisks_after_lines_without_commas(self):
        with open('assets/original_file.txt', 'w') as f:
            f.write("line1\nline2,part2\nline3\n")

        function()

        with open('assets/processed_file.txt', 'r') as f:
            content = f.read()

        expected_content = "line1\n************\nline2,part2\nline3\n************\n"
        self.assertEqual(content, expected_content)

    # File 'assets/original_file.txt' is empty
    def test_empty_original_file(self):
        with open('assets/original_file.txt', 'w') as f:
            pass
    
        function()
    
        with open('assets/processed_file.txt', 'r') as f:
            content = f.read()
    
        self.assertEqual(content, "")

    # All lines in 'assets/original_file.txt' contain commas
    def test_all_lines_with_commas(self):
        with open('assets/original_file.txt', 'w') as f:
            f.write("line1,part2\nline2,part2\nline3,part2\n")
    
        function()
    
        with open('assets/processed_file.txt', 'r') as f:
            content = f.read()
    
        expected_content = "line1,part2\nline2,part2\nline3,part2\n"
        self.assertEqual(content, expected_content)